---
title: "CS 422"
author: "Sujad Patel, A20500962"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    df_print: paged
---
## Excersice 2.1
```{r}
opts_knit$set(progress=FALSE, verbose=FALSE)
```
###  Part i

```{r}
setwd( "/home/sp_wsl")
data.df <- read.csv('us-covid.csv', sep=',', skip = 7, header = T)
data.df
```

### Part ii

```{r}
library(dplyr)
mydata <- data.df
data.df <- select(mydata, -9)
data.df
```

### Part iii-a

```{r}
head(arrange(data.df,desc(total_cases)), 6)
```

### Part iii-b

```{r}
tail(arrange(data.df,desc(total_cases)), 6)
```

### Part iv

```{r}
library(psych)
pairs.panels(data.df[3:8], pch=21, main ="Correlation visualization")
```

### Part iv-a

```{r}
# We should exclude the first two columns because they are not necessary may increase the chance of noise, also the state are acting as ID and level has same value alla across the board
```

### Part iv-b

```{r}
# Total_cases and cases_last_7_days have the higest correlation.
```

### Part iv-c

```{r}
# case_rate_per_100k and cases_last_7_days have the lowest correlation.
```

### Part v-a

```{r}
options(scipen=999)
y <- rowSums(data.df[4:5])
plot(y, data.df$total_deaths, main ='Deaths per cases(confirmed + probable)', xlab ="Total cases", ylab = "Deaths", pch = 19, cex = 1.0, col = "blue")
```

### Part v-b

```{r}
# The data clearly shows the anomaly, since there are deaths reported while 0 having 0 cases in some sates. The reason for the anomaly is because some states only report total cases, therefore, probable and confirmed cases for these states gets recorded as 0. This creates a false data relation. 
```

### Part v-c

```{r}
select(filter(data.df, data.df$confirmed == 0 & data.df$probable == 0), 1,3,4,5,8)
```
