---
title: "R Notebook"
output: html_notebook
author: Sujad Patel
date: 10/30/22
---
## Part 2 Praticum Problems

```{r}
library(arules)
```

### 2.1 Association Analysis

```{r}
trans1 <- read.transactions("tr-1k-canonical.csv", sep=",")
trans5 <- read.transactions("tr-5k-canonical.csv", sep=",")
trans20 <- read.transactions("tr-20k-canonical.csv", sep=",")
trans75 <- read.transactions("tr-75k-canonical.csv", sep=",")

```

### 2.1.b

```{r}
t1 <-apriori(trans1, parameter=list(support=0.02, confidence=0.5, target="frequent itemsets"))
t20 <-apriori(trans20, parameter=list(support=0.02, confidence=0.5, target="frequent itemsets"))
t5 <-apriori(trans5, parameter=list(support=0.01, confidence=0.5, target="frequent itemsets"))
t75 <-apriori(trans75, parameter=list(support=0.01, confidence=0.5, target="frequent itemsets"))

```

```{r}
inspect(sort(t1, decresing=T, by="count"))
inspect(sort(t5, decresing=T, by="count"))
inspect(sort(t20, decresing=T, by="count"))
inspect(sort(t75, decresing=T, by="count"))

```

```{r}
rules1k <-apriori(trans1, parameter = list(support=0.01))
rules5k <-apriori(trans5, parameter = list(support=0.01))
rules20k <-apriori(trans20, parameter = list(support=0.01))
rules75k <-apriori(trans75, parameter = list(support=0.01))


```

```{r}
cat("Rules generated by tr1K")
inspect(sort(rules1k, by="confidence"))
```

```{r}
cat("Rules generated by tr5K")
inspect(sort(rules5k, by="confidence"))
```

```{r}
cat("Rules generated by tr20K")
inspect(sort(rules20k, by="confidence"))
```

```{r}
cat("Rules generated by tr75K")
inspect(sort(rules75k, by="confidence"))
```

### 2.1.c

```{r}
#Setting the support constant in generating rules for all subsets, there is not much difference. Even the number of rules generated are similar accross the subset.
```

### 2.1.d
```{r}
# (i) The most frequently purchased item is {Coffe Eclair} with count of 8193.
# (ii)The least frequently purchased itemset is	{Apple Croissant, Apple Danish, Apple Tart, Cherry Soda} with count of 1544.

```
